### ISSUE TITLE
Error migrating contracts in  v0.6.9

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/keeper-contracts#275]
## Current Behavior
I am trying to execute the following command using barge `KEEPER_VERSION=v0.6.9 bash -x start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node` and it is given me an error when it is trying to migrate the contracts.

## Step to Reproduce the problem

1. `KEEPER_VERSION=v0.6.9 bash -x start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node`

### Possible Solution
It looks that is trying to do the migration with an account that is locked.
## Failure Logs
```
keeper-contracts_1           | Writing artifacts to ./build/contracts
keeper-contracts_1           | 
keeper-contracts_1           | Setting up MultiSigWallet
keeper-contracts_1           | gasLimit 5930063947 multiSigAccounts [
keeper-contracts_1           |   "0x0011598De1016A350ad719D23586273804076774",
keeper-contracts_1           |   "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e",
keeper-contracts_1           |   "0x068Ed00cF0441e4829D9784fCBe7b9e26D4BD8d0",
keeper-contracts_1           |   "0x6B0c56d1Ad5144b4d37fa6e27DC9afd5C2435c3B"
keeper-contracts_1           | ] threshold 2
keeper-contracts_1           | Error: Returned error: Your account is locked. Unlock the account via CLI, personal_unlockAccount or use Trusted Signer.
keeper-contracts_1           |     at Object.ErrorResponse (/keeper-contracts/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/~/web3-core-helpers/src/errors.js:29:1)
keeper-contracts_1           |     at /keeper-contracts/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:140:1
keeper-contracts_1           |     at /keeper-contracts/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
keeper-contracts_1           |     at XMLHttpRequest.request.onreadystatechange (/keeper-contracts/node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:96:1)
keeper-contracts_1           |     at XMLHttpRequestEventTarget.dispatchEvent (/keeper-contracts/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
keeper-contracts_1           |     at XMLHttpRequest._setReadyState (/keeper-contracts/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
keeper-contracts_1           |     at XMLHttpRequest._onHttpResponseEnd (/keeper-contracts/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
keeper-contracts_1           |     at IncomingMessage.<anonymous> (/keeper-contracts/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
keeper-contracts_1           |     at IncomingMessage.emit (events.js:187:15)
keeper-contracts_1           |     at endReadableNT (_stream_readable.js:1094:12)
keeper-contracts_1           |     at process._tickCallback (internal/process/next_tick.js:63:19)
keeper-contracts_1           | Truffle v5.0.2 (core: 5.0.2)
keeper-contracts_1           | Node v10.15.0
keeper-contracts_1           | npm ERR! code ELIFECYCLE
keeper-contracts_1           | npm ERR! errno 1
keeper-contracts_1           | npm ERR! @oceanprotocol/keeper-contracts@0.6.9 migrate: `./scripts/deployContracts.sh "--network=spree"`
keeper-contracts_1           | npm ERR! Exit status 1
keeper-contracts_1           | npm ERR! 
keeper-contracts_1           | npm ERR! Failed at the @oceanprotocol/keeper-contracts@0.6.9 migrate script.
keeper-contracts_1           | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
keeper-contracts_1           | 
keeper-contracts_1           | npm ERR! A complete log of this run can be found in:
keeper-contracts_1           | npm ERR!     /root/.npm/_logs/2019-01-22T08_20_37_026Z-debug.log
```

**Comment by H34D** [comment]
closes with #282
