### ISSUE TITLE
Deploying keeper-contracts to `ganache-cli` fails with sender account not recognized error

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/keeper-contracts#279]
Deploying keeper-contracts to `ganache-cli` fails with this error:
```
[SimpleProject] Deploying logic contract for PaymentConditions
[Error] Error: DIDRegistry deployment failed with error: Error: sender account not recognized
OceanToken deployment failed with error: Error: sender account not recognized
Dispenser deployment failed with error: Error: sender account not recognized
ServiceExecutionAgreement deployment failed with error: Error: sender account not recognized
AccessConditions deployment failed with error: Error: sender account not recognized
FitchainConditions deployment failed with error: Error: sender account not recognized
ComputeConditions deployment failed with error: Error: sender account not recognized
PaymentConditions deployment failed with error: Error: sender account not recognized
    at allPromisesOrError (/home/ssallam/pycharm_projects/keeper-contracts/node_modules/zos/lib/utils/async.js:36:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ZosNetworkFile] Created zos.dev-1548166950291.json
```

This was produced using this command: `npm run migrate`

**Comment by H34D** [comment]
@ssallam please do `rm wallet.json` before migrating as a workaround.

**Comment by H34D** [comment]
i have rewritten the deployment script in node #274

**Comment by H34D** [comment]
should close with #282
