### ISSUE TITLE
Securify Report generation fails in Travis

### ISSUE THREAD

**Issue by aabdulwahed** [oceanprotocol/keeper-contracts#283]
```bash
Compiling project
Traceback (most recent call last):
  File "/sec/scripts/solc_project.py", line 97, in _compile_solfiles
    stdoutdata, _, _, _ = solc_wrapper(**compiler_kwargs)
  File "/root/.local/lib/python3.6/site-packages/solc/utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/root/.local/lib/python3.6/site-packages/solc/wrapper.py", line 169, in solc_wrapper
    stderr_data=stderrdata,
solc.exceptions.SolcError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker_run_securify.py", line 25, in <module>
    return_code = ctrler.compile_and_report()
  File "/sec/scripts/controller.py", line 77, in compile_and_report
    return self._project.execute()
  File "/sec/scripts/project.py", line 68, in execute
    self.compile_(compilation_output)
  File "/sec/scripts/solc_project.py", line 52, in compile_
    comp_output = self._compile_solfiles(sources)
  File "/sec/scripts/solc_project.py", line 100, in _compile_solfiles
    raise utils.SolidityCompilationException(e, files)
scripts.utils.SolidityCompilationException: <exception str() failed>
```

For more info, checkout [keeper-contracts-security-reports](https://github.com/oceanprotocol/keeper-contracts-security-reports)

**Comment by H34D** [comment]
why is this not failing the build?

**Comment by H34D** [comment]
> @H34D we bypass the output in `STDOUT` as travis stdout fails to render all the outputs (too much information).

what about `STDERR`?

**Comment by jcortejoso** [comment]
I have been testing locally with old `﻿chainsecurity/securify:latest` images and happens the same error. I have been testing commit by commit and it breaks in this commit: https://github.com/oceanprotocol/keeper-contracts/commit/ab58f07152754d0b6a29f8632f0510e7f5ec9736

**Comment by H34D** [comment]
lets move this to k8s
