### ISSUE TITLE
Error running v0.6.10 in barge using spree node

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/keeper-contracts#296]
Fails with deployment error:
```
keeper-contracts_1           | Error: Mnemonic invalid or undefined
keeper-contracts_1           |     at new v (/keeper-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/src/index.js:50:1)
keeper-contracts_1           |     at setupWallet (/keeper-contracts/truffle.js:14:18)
keeper-contracts_1           |     at Object.provider (/keeper-contracts/truffle.js:45:29)
keeper-contracts_1           |     at Object.create (/keeper-contracts/node_modules/truffle/build/webpack:/packages/truffle-provider/index.js:15:1)
keeper-contracts_1           |     at Config.get [as provider] (/keeper-contracts/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:202:1)
keeper-contracts_1           |     at Object.detect (/keeper-contracts/node_modules/truffle/build/webpack:/packages/truffle-core/lib/environment.js:59:1)
keeper-contracts_1           |     at Object.run (/keeper-contracts/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/exec.js:60:1)
keeper-contracts_1           |     at Command.run (/keeper-contracts/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:113:1)
keeper-contracts_1           |     at Object.<anonymous> (/keeper-contracts/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:47:1)
keeper-contracts_1           |     at __webpack_require__ (/keeper-contracts/node_modules/truffle/build/webpack:/webpack/bootstrap 07e85fa5d55682c1e7c6:19:1)
keeper-contracts_1           |     at /keeper-contracts/node_modules/truffle/build/webpack:/webpack/bootstrap 07e85fa5d55682c1e7c6:65:1
keeper-contracts_1           |     at Object.<anonymous> (/keeper-contracts/node_modules/truffle/build/cli.bundled.js:71:10)
keeper-contracts_1           |     at Module._compile (internal/modules/cjs/loader.js:689:30)
keeper-contracts_1           |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
keeper-contracts_1           |     at Module.load (internal/modules/cjs/loader.js:599:32)
keeper-contracts_1           |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
keeper-contracts_1           |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
keeper-contracts_1           |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
keeper-contracts_1           |     at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
keeper-contracts_1           | Truffle v5.0.2 (core: 5.0.2)
keeper-contracts_1           | Node v10.15.0
keeper-contracts_1           | npm ERR! code ELIFECYCLE
keeper-contracts_1           | npm ERR! errno 1
keeper-contracts_1           | npm ERR! @oceanprotocol/keeper-c
```

**Comment by H34D** [comment]
fixed with this: https://github.com/oceanprotocol/barge/commit/280c142b775377731b1ab746213e60f002daca55
