### ISSUE TITLE
Error starting keeper-contracts v0.8.3 using barge

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/keeper-contracts#415]
# Prerequisites

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository.

## Expected Behavior

When I'm trying to run keeper-contracts 0.8.3 using barge (spree) is failing in the deployment phase. 

## Current Behavior

ABI artifacts are not being generated for the spree network

## Failure Information (for bugs)

```
keeper-contracts_1           | [BaseSimpleProject] Creating proxy to logic contract 0xc76169f4973d867f42B909c8bfA1d40C62c5e23b and initializing by calling initialize with: 
keeper-contracts_1           |  - _owner (address): "0xA43335345B4afc9c0d407d44B3483090E1a115d5"
keeper-contracts_1           |  - _agreementStoreManagerAddress (address): "0xC928f5299f72Aac803fC7fa753B14f174148dc15"
keeper-contracts_1           |  - _didRegistryAddress (address): "0x8C97289d29bb558D21f2a00f4D2099c3ae10d685"
keeper-contracts_1           |  - _accessSecretStoreConditionAddress (address): "0x0e7319A14Ac97926A3d547be5707a314759C0309"
keeper-contracts_1           |  - _lockRewardConditionAddress (address): "0x1EdE04f6D0C2E636627587D1f2186bBFb9901E91"
keeper-contracts_1           |  - _escrowRewardAddress (address): "0xAe586560868116e386a1C15A3Ad3F548ECfCf9a3"
keeper-contracts_1           | [BaseSimpleProject] Instance created at 0x5a55D37CFD16c6f1c6d7FbE2f56c27CADBf6A67A
keeper-contracts_1           | [ZosNetworkFile] Updated zos.dev-8996.json
keeper-contracts_1           | Error: Transaction nonce is too low. Try incrementing the nonce.
keeper-contracts_1           |     at /keeper-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/subproviders/provider.js:18:1
keeper-contracts_1           |     at e.callback [as onreadystatechange] (/keeper-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-providers-http/src/index.js:96:1)
keeper-contracts_1           |     at e.call [as dispatchEvent] (/keeper-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
keeper-contracts_1           |     at e.dispatchEvent [as _setReadyState] (/keeper-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
keeper-contracts_1           |     at e._setReadyState [as _onHttpResponseEnd] (/keeper-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
keeper-contracts_1           |     at IncomingMessage._onHttpResponseEnd (/keeper-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
keeper-contracts_1           |     at IncomingMessage.emit (events.js:194:15)
keeper-contracts_1           |     at endReadableNT (_stream_readable.js:1125:12)
keeper-contracts_1           |     at process._tickCallback (internal/process/next_tick.js:63:19)
keeper-contracts_1           | Truffle v5.0.7 (core: 5.0.7)
keeper-contracts_1           | Node v10.15.3
keeper-contracts_1           | npm ERR! code ELIFECYCLE
keeper-contracts_1           | npm ERR! errno 1
keeper-contracts_1           | npm ERR! @oceanprotocol/keeper-contracts@0.8.3 deploy: `npx truffle exec ./scripts/deploy/truffle-wrapper/deployContractsWrapper.js "--network" "spree"`
keeper-contracts_1           | npm ERR! Exit status 1
keeper-contracts_1           | npm ERR! 
keeper-contracts_1           | npm ERR! Failed at the @oceanprotocol/keeper-contracts@0.8.3 deploy script.
keeper-contracts_1           | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
keeper-contracts_1           | 
keeper-contracts_1           | npm ERR! A complete log of this run can be found in:
keeper-contracts_1           | npm ERR!     /root/.npm/_logs/2019-03-12T09_07_43_477Z-debug.log
```

## Step to Reproduce the problem

```
docker image prune -a
KEEPER_VERSION=v0.8.3 bash start_ocean.sh --latest --no-pleuston --local-spree-node --force-pull
```

**Comment by H34D** [comment]
fixed with `v0.8.5`
